### ISSUE TITLE
[Q] How to install "taiga-contrib-slack" plugin in a Dockerized Taiga ?

### ISSUE THREAD

**Issue by franck-grenier** [taigaio/taiga-contrib-slack#1]
Hello,
I'm trying to install your "taiga-contrib-slack" plugin in a Dockerized Taiga based on `dockertaiga/back:6.2.0` and `dockertaiga/front:6.2.0` images.

Following your installation steps seems quite painful in my setup. I have to install prerequisites like Git and a lot of pip packages (django, wheel, kombu, psycopg2...) in my running container and `pip install` is crashing on these missing dependencies. I'm not sure I'm going on the right path...

Thought it would be easier to install Taiga plugins. :cry: 

Could you provide with some help ?

Thanks !

**Comment by franck-grenier** [comment]
Ok I got it.

Some dependencies needed inside the `back` container : 

```
apk update && apk upgrade && apk add --no-cache bash git openssh
source .venv/bin/activate
pip install psycopg2 kombu django wheel
```
Then still in the `(taiga-back)` virtual env, install the plugin : 

```
pip install "git+https://github.com/kaleidos-ventures/taiga-contrib-slack.git@${TAIGA_CONTRIB_SLACK_TAG}#egg=taiga-contrib-slack&subdirectory=back"
```
Update the `settings/local.py` config : 

```
INSTALLED_APPS += ["taiga_contrib_slack"]
```
Then still in the `(taiga-back)` virtual env, run migrations : 

```
python manage.py migrate taiga_contrib_slack
```
My mistake : I was not running the migrations in the `(taiga-back)` virtual env.

**Comment by bameda** [comment]
Hi @franck-grenier,

the slack pluging is included by default in the docker instances so you only need to enabled it, that's all. According to the [30' setup guide](https://resources.taiga.io/30min-setup/#slack-settings):

> ### Slack Settings
> 
> Service: taiga-back
> ```
> ENABLE_SLACK: "True"
> ```
>
> Service: taiga-front
> ```
> ENABLE_SLACK: "true"
> ```
>
> Enable Slack integration in your Taiga instance. By default is _“False”_. Should have the same value as this variable in `taiga-front` and `taiga-back`.

Best regards.

**Comment by SheryarKhaliq125** [comment]
@bameda i followed the instructions but it is not working.

i cannot see slack, can you please help me.

![{4014EF05-7D68-4064-8EF5-2B26189B6C55}](https://github.com/user-attachments/assets/1f0cf335-3fe0-4fa4-bc50-2d7a6c8ed8d9)

**Comment by TsukiGva2** [comment]
I had the same problem, turns out i put True instead of "True", both should be quoted.
