### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by GQAdonis** [taigaio/taiga-contrib-slack#10]
I am getting the following error when I try to install using "pip install taiga-contrib-slack":

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eD47Zm/taiga-contrib-slack

Can someone help with this?

**Comment by bameda** [comment]
You try to install the plugin with python 2 instead with python 3

If you use a virtualenv for install taiga-back, you have to install the plugin in this virtualenv, so try with 

```
workon taiga
pip install taiga-contrib-slack
```
