### ISSUE TITLE
Some special character don't display correctly

### ISSUE THREAD

**Issue by IwishIcanFLighT** [taigaio/taiga-contrib-slack#11]
Hi !
I noticed a bug with the plugin lately. Some special characters don't display correctly in the slack messages. So far I found ' and " not working, but there might be others...

### Kanban view

![kanban_view](https://cloud.githubusercontent.com/assets/4090502/6917758/f3ac85b0-d7a7-11e4-9311-d119c06151af.PNG)

### Slack view

![slack_view](https://cloud.githubusercontent.com/assets/4090502/6917759/f3afe2be-d7a7-11e4-8e6d-cfd56166a4ce.PNG)

**Comment by superalex** [comment]
Thanks @IwishIcanFLighT it should be solved with this PR :+1:

**Comment by IwishIcanFLighT** [comment]
After testing, the issue seems to be fixed with the latest version. Thanks a lot @superalex ! :+1:

**Comment by superalex** [comment]
You are welcome! :)
