### ISSUE TITLE
Would it be possible to add the ability to change the channel?

### ISSUE THREAD

**Issue by Madhotdog** [taigaio/taiga-contrib-slack#16]
When you have multiple projects on Taiga, it can be useful to post the Slack notifications to different channels. Would it be possible to add this functionality to this plug-in?

**Comment by superalex** [comment]
Yes it would be possible, but it will need some development :)

**Comment by Madhotdog** [comment]
I had a go at implementing it myself. Python isn't really my jam, so let me know if there are any issues :)

**Comment by superalex** [comment]
Thanks @Madhotdog, I'm checking your pull request! :+1:
