### ISSUE TITLE
ImportError: cannot import name 'get_typename_for_model_instance'

### ISSUE THREAD

**Issue by aliirz** [taigaio/taiga-contrib-slack#2]
I get the above error when I run ```python manage.py migrate taiga_contrib_slack``` please help..Also does this allow Slack creds to be entered via UI or do I have to fork and edit tasks.py myself?

**Comment by bameda** [comment]
Hi @aliirz 

This app will be compatible with Taiga 1.5.0 that has not been released yet (maybe next tuesday or wednesday). Please, wait to next week or use our unstable branch (master) of taiga-back and taiga-front(-dist) to tests this feature in a **non-production** environments.

Thanks.

**Comment by aliirz** [comment]
Thanks bameda.

**Comment by bameda** [comment]
You are welcome. 

Next week we'll update the documentation and the support page to explain this new integration and all the new features.

**Comment by aliirz** [comment]
Also is there a Roadmap for people to contribute to? I can help maintain the front certainly

**Comment by bameda** [comment]
When public projects are available, we'll publish the Taiga project at taiga.io. For the next releases we want to make the custom fields for issues, tasks and user stories, and the ability to extract this information to a csv file or something similar, make front to be translatable...

The best way to stay abreast of what is happening or will happen is reading our blog (blog.taiga.io) or our mailing list (https://groups.google.com/forum/#!forum/taigaio) or the CHANGELOG files of the different repositories.

https://github.com/taigaio/taiga-front/blob/master/CHANGELOG.md
https://github.com/taigaio/taiga-back/blob/master/CHANGELOG.md

There are a lot of ways to help taiga project, but I think the best way is with features that are win-win. Which type of features do you miss in taiga and want to work on? Some interesting ways of collaboration are client libraries to the api in any language, other type of clients like command line clients, informational document generators using Taiga API, integration with third party services like hipchat, importers from other software like jira, trac, mantis, pivotal tracker, trello...

Of course if you chose one feature to be implemented you will have our help and suggestions to implement it and make the pull-request easier to be accepted :)

You can find more info about this at https://taiga.io/support/how-can-i-contribute-to-taiga/

Regards
