### ISSUE TITLE
Weird messages generated from webhooks in slack

### ISSUE THREAD

**Issue by haikyuu** [taigaio/taiga-contrib-slack#21]
After creating an issue in github, i get this message in slack. I have github integration enabled.
 ![capture](https://cloud.githubusercontent.com/assets/8558836/8108933/f3f91ab2-1053-11e5-9e23-e8c95f08786f.PNG)
It's not very readable

**Comment by superalex** [comment]
Thanks for reporting @haikyuu 

It's a problem related to the markdown format, I think @bameda had some ideas about how to solve it.

We have created an issue in Taiga for working on this one -> https://tree.taiga.io/project/taiga/issue/2941

Regards,

**Comment by jespino** [comment]
Fixed in the merged PR#25
