### ISSUE TITLE
Notifications not being sent to slack even though test is successful

### ISSUE THREAD

**Issue by seagoj** [taigaio/taiga-contrib-slack#27]
I have a bit of a weird issue. I've upgraded taiga (to 1.8) and installed the plugin following your procedure and I thought everything was successful. Hitting the 'Test' button sends a message to the right slack channel, but I get no further messages. I've created and modified issues and user stories and no joy. I even tried creating a new project and creating issues there and nothing ever comes through.

Thanks in advance

**Comment by bameda** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/taigaio/OqVfw4StVgE/7IRFWqhzaWEJ
