### ISSUE TITLE
mistype .js and .json in README.md

### ISSUE THREAD

**Issue by aatangulov** [taigaio/taiga-contrib-slack#35]
When you do `svn export "https://github.com/taigaio/taiga-contrib-slack/tags/$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}')/front/dist" "slack"`  we are getting slack.js, not slack.json.
But readme tell us point to "/plugins/slack/slack.json".
The same issue with taiga-contrib-github-auth, taiga-contrib-gogs and taiga-contrib-hipchat.

**Comment by bameda** [comment]
Yes, because this instructions are for the next versión, follow this: https://github.com/taigaio/taiga-contrib-slack/blob/2fe5b86d5807b4d81c03c965df8fb8db368b7fc8/README.md
