### ISSUE TITLE
How debug outgoing payload?

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-contrib-slack#36]
I've got this plugin mostly working with a chat system which is supposed to be 100% compatible with Slack's API. The plugin is posted to the channel but without any content.

![rocket_chat](https://cloud.githubusercontent.com/assets/76320/12006666/fdefaeb2-abd7-11e5-9332-8513d91dd4fc.jpg)

I'd like to know whether the correct payload is being posted to the chat application from Taiga, is it possible to see this in some logs somewhere?

**Comment by tanc** [comment]
ok, I've got my messages showing in my chat application now. I had to change the format of the payload though, so in _send_request I'm using `requests.post(url, json=data)` instead of `requests.post(url, json=serialized_data)`

Is there a reason why this works and the other method doesn't?

**Comment by bameda** [comment]
I don't understand your question, I don't know if you are modifying the plugin code for creating a new one. If you show your code maybe I can help you better. But I'll try it:

```json``` kwarg is for python objects and ```serialized_data``` is a json object. So you have to use

```
requests.post(url, json=data)
```
or 
```
requests.post(url, data=serialized_data)
```

**Comment by tanc** [comment]
Hi @bameda, thanks for getting back to me. I'm trying to get this plugin (taiga-contrib-slack) working with [rocket.chat](https://rocket.chat) which has (supposedly) a 100% Slack compatible API. For some reason that I'm trying to establish rocket.chat will only display messages which use `requests.post(url, json=data)` rather than `requests.post(url, data=serialized_data)`

Using the serialized_data results in an empty message, as shown in my first post. Changing to `json=data` sends the payload across in a way that rocket.chat can consume correctly. So rather than modify this plugin code as I'm currently having to do, I'd like to establish where the problem is so I can help rocket.chat (also open source) make their API fully Slack compatible. Unfortunately I don't know Python at all so I'm having to ask for help. I'd like to understand how the two payloads are different, why one works and the other doesn't. Any advice appreciated.

**Comment by tanc** [comment]
My currently working code:

```python
def _send_request(url, data):

    if settings.CELERY_ENABLED:
        requests.post(url, json=data)
        return

    try:
        requests.post(url, json=data)
    except Exception:
        logger.error("Error sending request to slack")
```

**Comment by tanc** [comment]
I've been able to get the serialized_data posting correctly but only when specifying custom headers for JSON like so:

```Python
def _send_request(url, data):
    serialized_data = UnicodeJSONRenderer().render(data)
    headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}

    if settings.CELERY_ENABLED:
        requests.post(url, data=serialized_data, headers=headers)
        return

    try:
        requests.post(url, data=serialized_data, headers=headers)
    except Exception:
        logger.error("Error sending request to slack")
```

Does this mean that specifying the kwarg `json=data` automatically changes the headers? I'm unsure of where the issue is occurring at this point as I'm not sure how to debug the outgoing request and view the headers. Is this a rocket.chat issue or this plugin's issue?

**Comment by tanc** [comment]
A bit more on this. Using r.request.headers and the three variations I get the following headers for each:

`requests.post(url, data=serialized_data)` = `{'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.8.1', 'Content-Length': '132'}`

`requests.post(url, json=data)` = `{'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Content-Type': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '132', 'User-Agent': 'python-requests/2.8.1'}`

`requests.post(url, data=serialized_data, headers=headers)` = `{'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/plain', 'User-Agent': 'python-requests/2.8.1', 'Content-type': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '132'}`

So it would appear that the only requirement from rocket.chat is that the headers contain `'Content-type': 'application/json'` which only happens if using `json=data` or by specifying the header. Is there any reason not to add the header if JSON data is being sent?

**Comment by bameda** [comment]
If you reed the [documentation of the requests lib](http://docs.python-requests.org/en/latest/user/quickstart/#more-complicated-post-requests) you can find the explanation about this behavior:

- ```request.post(url, data=payload)``` make a POST to the ```url``` and ```data``` parameter will automatically be form-encoded.
- ```request.post(url, json=plain_test)``` make a POST to the ```url``` and ```json``` parameter will be encoded as json object.

**Comment by tanc** [comment]
My question still stands: Is there any reason not to add the header if JSON data is being sent?

**Comment by bameda** [comment]
No, I think that the slack API doesn't need it.

**Comment by tanc** [comment]
Ok cool, thats fair enough. The developers at rocket.chat have flagged the issue as a bug at their end so that they can make it the same as Slack and accept any header.

**Comment by engelgabriel** [comment]
Indeed, it's not mandatory. Per the HTTP 1.1 specification:

> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

That said, it's obviously going to be hard for the server to accurately interpret the data you're sending if you omit the Content-Type header, so it's not recommended to do so.

We had to hack the NodeJS lib, as it would refuse to try to guess the content type.

**Comment by bameda** [comment]
Yes, I prefer to send the content-type too: explicit better than implicit.
