### ISSUE TITLE
Plugin settings section error after upgrading to 1.9.1

### ISSUE THREAD

**Issue by yuters** [taigaio/taiga-contrib-slack#37]
I've tried upgrading the plugin after upgrading taiga to 1.9.1 and got a blank page after following the installation instructions. Then I found out the file slack.json was missing in `plugins/slack/` (there was only a slack.js file)

After this taiga worked normally, but when going to the plugins setting the slack menu is duplicated and it infinitely loads the settings page:

<img width="1334" alt="screen shot 2016-01-06 at 1 19 47 pm" src="https://cloud.githubusercontent.com/assets/801718/12150523/36d575c4-b478-11e5-8b14-e599b53dad9c.png">

**Comment by bameda** [comment]
Hi @yuters what files are in plugins/slack? What do you have in your config.json?

**Comment by yuters** [comment]
```
dist/plugins/slack/slack.js
dist/plugins/slack/slack.json
```

slack.json
```
{
    "name": "Slack",
    "slug": "slack",
    "description": "Integrate Taiga with Slack (https://slack.com)",
    "type": "admin",
    "module": "taigaContrib.slack",
    "template": "plugin/slack",
    "js": "/plugins/slack/slack.js"
}
```

**Comment by bameda** [comment]
In ``taiga-front-dist/dist/config.json`

**Comment by yuters** [comment]
```
{
    "api": "http://localhost:8000/api/v1/",
    "eventsUrl": null,
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": ["/plugins/slack/slack.json"]
}
```

**Comment by bameda** [comment]
Try to show if there is an error in the browser console. Your config file is ok

**Comment by yuters** [comment]
A bunch of
```
WARNING: Tried to load angular more than once.
```

It's just loading the same thing over and over again, after a while I get this errors:
```
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! angular.js:68
````
And then it starts all over again.

**Comment by yuters** [comment]
Alright, I just found out it only happens in Chrome v48.0.2564.71 (No problem in Safari or Firefox). I'm on Mac OS X. I thought it might be an extension but it's the same thing with all chrome extensions disabled.

**Comment by superalex** [comment]
Hello @yuters 

Could you try if it's happening too on tree.taiga.io?, we should have the same version of the plugin deployed.

**Comment by yuters** [comment]
No problem there. Deleting my cache solved the issue on my side... looks like it took more than a hard reload, sorry about that :)

**Comment by superalex** [comment]
Great! :)
