### ISSUE TITLE
Slack plugin breaks latest Taiga 

### ISSUE THREAD

**Issue by Trefex** [taigaio/taiga-contrib-slack#39]
When loading slack plugin in latest Taiga, the front renders a white page.

There's no visible errors anywhere.

Upon removing the slack plugin, Taiga works fine.

Could you please investigate?

**Comment by bameda** [comment]
What version of Taiga are you using? What version of the plugin are you using?

**Comment by Trefex** [comment]
Latest, no idea how to see version number in taiga?

Plugin, I pulled latest from svn, using your Doc. Same question, no clue where to find it.

Now it seems with latest version, that the page loads, but I just get a taiga loading wheel, and a process 

    python -c from circus import stats; main.stats() ...


taking 4% CPU and nothing else happens.

**Comment by Trefex** [comment]
(taiga)taiga@taiga-lcsb:~/taiga-back$ pip show taiga-contrib-slack
    ---
    Name: taiga-contrib-slack
    Version: 1.10
    Location: /home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages
    Requires:

**Comment by Trefex** [comment]
Taiga version v-1454071457968 I guess?

**Comment by bameda** [comment]
```
workon taiga
cd taiga-back
git describe --tags 
(....)
pip show taiga-contrib-slack
(...)
cd ../taiga-front-dist
git describe --tags 
(...)
```

if all is 1.10* try to download the plugin again

```
cd dist/
mkdir -p plugins
cd plugins
svn export "https://github.com/taigaio/taiga-contrib-slack/tags/$(pip show taiga-contrib-slack | awk '/
```

And test it, showing the errors in the browser console

**Comment by Trefex** [comment]
`(taiga)taiga@taiga-lcsb:~/taiga-back$ git describe --tags
1.10.0-3-g5899a63`

`(taiga)taiga@taiga-lcsb:~/taiga-back$ pip show taiga-contrib-slack
---
Name: taiga-contrib-slack
Version: 1.10
Location: /home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages
Requires:`

`(taiga)taiga@taiga-lcsb:~/taiga-front-dist$ git describe --tags
1.10.0-stable`

**Comment by Trefex** [comment]
(taiga)taiga@taiga-lcsb:~/taiga-front-dist/dist$ cat conf.json
{
    "api": "https://taiga.lcsb.uni.lu/api/v1/",
    "eventsUrl": null,
    "debug": false,
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "debugInfo": false,
    "contribPlugins": [
        "/plugins/slack/slack.json"
    ]
}

**Comment by Trefex** [comment]
Well, gotta be magic, seems to work now...

Not sure what fixed it to be honest...

**Comment by bameda** [comment]
Browser cache is evil :smiling_imp:

**Comment by Trefex** [comment]
We did have this issue since Thursday or so. 

So my guess is, there's a combination of many factors :)

**Comment by rpatni** [comment]
Same problem occurred for me too..
I noticed when installing the slack integration was that it downgraded django to 1.8.5 while taiga 1.10 uses 1.8.6?
When Taiga stopped working, I did an upgrade again for taiga-back, then commented the slack plugin from local.py in taiga-back and conf.json in taiga-front and it started working.
Not sure what I need to do to re-enable?

**Comment by rpatni** [comment]
I tried re-enabling and restarted the server...seems to be working now!!

**Comment by rpatni** [comment]
Stopped working again!! Again, taiga responds faster and perfectly as soon as I turn off the integration!!

**Comment by bameda** [comment]
If the plugin downgrade djangois because you are using an old version. truy to reinstall the plugin:

```
workon taiga
pip install --upgrade taiga-contrib-slack
```
