### ISSUE TITLE
Customize the username on actions posted to slack?

### ISSUE THREAD

**Issue by joelabair** [taigaio/taiga-contrib-slack#4]
It would be great if we could send the username string in the slack payload for this integration.

**Comment by jespino** [comment]
I like the idea, but I'm not sure were put it. In the username of the payload somthing like Taiga (user name) or inside the content of the message (for example at the beginning or at the end) with the text "by user name".

Anyway, I want to keep the "Taiga" username at the start of the slack username, following the style of other integrations like Github.

**Comment by joelabair** [comment]
I like Taiga (Joel Bair) - looks awesome, and consistent appearance.   Currently I see "Taiga BOT" on most things.  Which is very generic.

**Comment by jespino** [comment]
Fixed in the PR #24 Will be available in the next release. Thanks again for your feedback. :smile_cat:
