### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by djneely** [taigaio/taiga-contrib-slack#43]
Working through the installation guide, the moment I bounce circus for the backend, the taiga system as a whole becomes unusable. I have to comment out the INSTALLED_APPS config option to bring the system back up.

Also, in the installation instructions the svn line:
svn export "https://github.com/taigaio/taiga-contrib-slack/tags/$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}')/front/dist" "slack"

Fails with:
svn: E170000: URL 'https://github.com/taigaio/taiga-contrib-slack/tags/front/dist' doesn't exist

**Comment by bameda** [comment]
Are you sure that you have installed the pip package of taiga-contrib-slack?

**Comment by bameda** [comment]
without the package

```bash
> workon taiga                
> pip show taiga-contrib-slack
> 
```
           
whit the package installed

```                                                                                                                            1
> workon taiga                
> pip show taiga-contrib-slack   
---
Metadata-Version: 2.0
Name: taiga-contrib-slack
Version: 2.1
Summary: The Taiga plugin for slack integration
Home-page: https://github.com/taigaio/taiga-contrib-slack
Author: Jesús Espino García
Author-email: jesus.espino@kaleidos.net
Installer: pip
License: AGPL
Location: /home/bameda/.virtualenvs/taiga/lib/python3.5/site-packages
Requires: 
Classifiers:
  Programming Language :: Python
  Development Status :: 4 - Beta
  Framework :: Django
  Intended Audience :: Developers
  License :: OSI Approved :: GNU Affero General Public License v3
  Operating System :: OS Independent
  Programming Language :: Python
  Topic :: Internet :: WWW/HTTP
>
```

**Comment by djneely** [comment]
Yes, here are the commands and the results:

`
(taiga)taiga@development-1:~/taiga-back$ pip install taiga-contrib-slack
Requirement already satisfied (use --upgrade to upgrade): taiga-contrib-slack in ./taiga/lib/python3.4/site-packages
Cleaning up...
(taiga)taiga@development-1:~/taiga-back$ cat settings/local.py | grep INSTALLED_APPS
INSTALLED_APPS += ["taiga_contrib_slack"]
(taiga)taiga@development-1:~/taiga-back$ python manage.py migrate taiga_contrib_slack
Trying import local.py settings...
Operations to perform:
  Apply all migrations: taiga_contrib_slack
Running migrations:
  No migrations to apply.
(taiga)taiga@development-1:~/taiga-back$ pip show taiga-contrib-slack
---
Name: taiga-contrib-slack
Version: 2.1
Location: /home/taiga/taiga-back/taiga/lib/python3.4/site-packages
Requires: 
`

**Comment by bameda** [comment]
and what happens if you run this?

```bash
workon taiga
./manage.py runserver
```

any error?

**Comment by djneely** [comment]
So, I finally got it. I think the issue was with how I instantiated my virtualenv. I was doing what I normally do in a python environment with 'source taiga/bin/activate' this was how I did the pip install. However once I did the 'workon taiga' pip was not showing the package installed. So, I re-installed and everything from the backend perspective is looking good now. Taiga is operating normally and the app is enabled.

Time to move onto the frontend configuration. Thank you for the help.

**Comment by djneely** [comment]
I do still see the issue with: 

```
svn export "https://github.com/taigaio/taiga-contrib-slack/tags/$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}')/front/dist" "slack"
svn: E170000: URL 'https://github.com/taigaio/taiga-contrib-slack/tags/front/dist' doesn't exist
```

So, as of now I've manually pulled the 2 files in manually. That should be fine right?

```
taiga@development-1:~/taiga-front-dist/dist/plugins/slack$ ls -l
total 16
-rw-r--r-- 1 taiga taiga 9665 May 23 17:49 slack.js
-rw-r--r-- 1 taiga taiga  253 May 23 17:49 slack.json
```

**Comment by bameda** [comment]
Great \o/ you are welcome.

Is a very common mistake install things in the wrong virtualenv or out of them.

To fix the problem with the front part try to run the svn command with the virtualenv enabled because `$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}')` is trying to get the installed version of the pip package. 

Or  with

```
svn export "https://github.com/taigaio/taiga-contrib-slack/tags/2.1/front/dist" "slack"
```

And in case you did not know I recommend you to use virtualenv-wrapper (https://virtualenvwrapper.readthedocs.io/en/latest/).

**Comment by djneely** [comment]
Thanks for your help fellas. Looks like I'm on the right path now. Again, I think the main issue was my 'workon' vs. 'source evn/bin/activate' as I'm used to using. Looks like I'm on the right path. Things are starting to jive.

**Comment by bameda** [comment]
:smile_cat:
