### ISSUE TITLE
Failed to load contrib-slack

### ISSUE THREAD

**Issue by chmodrs** [taigaio/taiga-contrib-slack#46]
Good morning!

I've tried to install slack plugin in my Taiga server, i follow the how to and the installing finished without problems... but when i tried access the plugin configuration, i get the following message: 

![image](https://cloud.githubusercontent.com/assets/18267655/17480018/311df0a2-5d4c-11e6-9b2c-8d24c86dbbf3.png)

and access log shows error 404, as bellow:
 

192.168.5.156 - - [08/Aug/2016:09:33:05 -0300] "POST /api/v1/issues HTTP/1.1" 201 1213 "http://taiga.company.com.br/project/fmpinheiro-produtos/issues?page=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2822.0 Safari/537.36"
192.168.5.152 - - [08/Aug/2016:09:33:05 -0300] "GET /api/v1/projects/by_slug?slug=mrsilva-teste HTTP/1.1" 200 7446 "http://taiga.company.com.br/project/mrsilva-teste/admin/third-parties/webhooks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
192.168.5.152 - - [08/Aug/2016:09:33:05 -0300] "GET /api/v1/webhooks?project=16 HTTP/1.1" 200 12 "http://taiga.company.com.br/project/mrsilva-teste/admin/third-parties/webhooks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
192.168.5.156 - - [08/Aug/2016:09:33:06 -0300] "GET /api/v1/issues?page=1&project=17 HTTP/1.1" 200 35988 "http://taiga.company.com.br/project/fmpinheiro-produtos/issues?page=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2822.0 Safari/537.36"
192.168.5.152 - - [08/Aug/2016:09:33:06 -0300] "GET /api/v1/projects/by_slug?slug=mrsilva-teste HTTP/1.1" 200 7446 "http://taiga.company.com.br/project/mrsilva-teste/admin/contrib/slack" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
**192.168.5.152 - - [08/Aug/2016:09:33:06 -0300] "GET /api/v1/slack?project=16 HTTP/1.1" 404 111 "http://taiga.company.com.br/project/mrsilva-teste/admin/contrib/slack" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"**
192.168.5.156 - - [08/Aug/2016:09:33:07 -0300] "GET /api/v1/projects/by_slug?slug=fmpinheiro-produtos HTTP/1.1" 200 14998 "http://taiga.company.com.br/project/fmpinheiro-produtos/issue/1405" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2822.0 Safari/537.36"

anyone have any idea what can be?

Thank you!

**Comment by jespino** [comment]
Looks like your taiga-back haven't the taiga-contrib-slack plugin working. Have you followed the taiga-back part instructions? Have you restarted your taiga-back service after that?

**Comment by chmodrs** [comment]
Good morning Jespino,

I had restarted the server and did not work, now only restarted the service taiga and did reload the settings and it worked perfectly.

Thank you for your help.

**Comment by jespino** [comment]
You are welcome. :smile:
