### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by nomorebugs** [taigaio/taiga-contrib-slack#52]
The installation of the newest version 3.0 with the command `pip install taiga-contrib-slack` on python 3.4 following the given instructions fails:
`RuntimeError: maximum recursion depth exceeded`
I finally tried to install it in a clean virtual environment. The pip.log is attached.
[pip.log.txt](https://github.com/taigaio/taiga-contrib-slack/files/505887/pip.log.txt)

Everything worked fine in a former version.

**Comment by corebyte** [comment]
I have also this problem.

**Comment by bameda** [comment]
try to upgrade `pip` and `versiontools` before

```
pip install --upgrade pip versiontools
```

**Comment by corebyte** [comment]
Works. Thanks!
