### ISSUE TITLE
Failed to download contrib-slack in Taiga 3

### ISSUE THREAD

**Issue by chmodrs** [taigaio/taiga-contrib-slack#54]
Hi everybody.

I'm updating my Taiga 2.1 to 3.0 to get Gogs integration, but my slack plugin doesn't work.

When im tried to install taiga-contrib-slack i have this error:

> File "/home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version
> 
>     return self.__base.get_version(self)
> 
> RuntimeError: maximum recursion depth exceeded
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack
> Storing debug log for failure in /home/taiga/.pip/pip.log

and im pip.log have the error:

> Cleaning up...
>   Removing temporary dir /home/taiga/.virtualenvs/taiga/build...
> Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack
> Exception information:
> Traceback (most recent call last):
>   File "/home/taiga/.virtualenvs/taiga/local/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "/home/taiga/.virtualenvs/taiga/local/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
>     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
>   File "/home/taiga/.virtualenvs/taiga/local/lib/python3.4/site-packages/pip/req.py", line 1229, in prepare_files
>     req_to_install.run_egg_info()
>   File "/home/taiga/.virtualenvs/taiga/local/lib/python3.4/site-packages/pip/req.py", line 325, in run_egg_info
>     command_desc='python setup.py egg_info')
>   File "/home/taiga/.virtualenvs/taiga/local/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
>     % (command_desc, proc.returncode, cwd))
> pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack

i remove INSTALLED_APPS line from taiga-back/settings/local.py before upgrade my taiga enviroment.

Somebody help me in this issue? I'm doing something wrong?

Thank you

**Comment by bameda** [comment]
There is a lot of issues like this https://github.com/taigaio/taiga-contrib-slack/search?q=RuntimeError%3A+maximum+recursion+depth+exceeded&type=Issues&utf8=%E2%9C%93

To fix it

```
workon taiga
pip install --upgrade pip versiontools
```
and then reinstall the plugin.
