### ISSUE TITLE
[Mattermost] Links on messages won't display correctly

### ISSUE THREAD

**Issue by ChrisKaun** [taigaio/taiga-contrib-slack#55]
Hey,

yesterday I upgraded taiga and taiga-contrib-slack to the newest versions but run into a minor issue.
When I create an issue the message heads displays the complete URL instead of a link to the issue. When I change (close, change the name, etc) the link is properly displayed.
Here's a example:
![slack](https://cloud.githubusercontent.com/assets/10511539/19103741/0deef922-8ad9-11e6-9608-9fff80640d78.png)

We are using Mattermost instead of Slack but never run into any errors before.

Also it seems that there is no epic support at the moment, are there updates planned when epic support is added?

Regards,
Chris

**Comment by bameda** [comment]
Hi @ChrisKaun it seems a problem with Mattermost because I test it in slack and is working fine.

Epics are working fine too. Have you activated epics and related user stories notifications in Admin > Plugins > Slack?

**Comment by ChrisKaun** [comment]
Hey @bameda,
I don't have any options in the webinterface for epics. Is there anything that needs to be set when I update taiga-contrib-slack? I only updated the plugin with pip as mentioned in [this issue](https://github.com/taigaio/taiga-contrib-slack/issues/50).

    (taiga)taiga@task:~/taiga-back$ pip show versiontools
    ---
    Metadata-Version: 1.1
    Name: versiontools
    Version: 1.9.1

    (taiga)taiga@task:~/taiga-back$ pip show taiga-contrib-slack
    ---
    Metadata-Version: 1.1
    Name: taiga-contrib-slack
    Version: 3.0.1

Seems to me that the upgrade was successfull.

**Comment by bameda** [comment]
And the front? Have you updated the front?

Follow steps at https://github.com/taigaio/taiga-contrib-slack

**Comment by ChrisKaun** [comment]
Thanks, that seems to be the issue for the epics.

**Comment by bameda** [comment]
Great
