### ISSUE TITLE
Not showing up in UI

### ISSUE THREAD

**Issue by JohnDorien1** [taigaio/taiga-contrib-slack#67]
I installed the plugin as described in Production section here: https://github.com/taigaio/taiga-contrib-slack
Taiga is latest version.

There's nothing showing up in UI and there's nothing in the log files. Browser cache was emptied for testing but also no result.

Any ideas or hints?

**Comment by theriverman** [comment]
Can you show the contents of your `dist/conf.json` file from taiga-front?

**Comment by JohnDorien1** [comment]
``
    "api": "https://domain.tld/api/v1/",
    "eventsUrl": "wss://domain.tld/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "supportUrl": "https://domain.tld",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": ["/plugins/slack/slack.json"],
    "tribeHost": null,
    "importers": [],
    "gravatar": true
}
``

**Comment by JohnDorien1** [comment]
Ok for whatever reason after a couple of restarts it's now visible and available. Strange.

**Comment by morphatic** [comment]
I have this exact same problem. I have restarted the server. I have restarted `circusd` and `nginx` and still I don't see any plugins or options for plugins in the UI. I'm using the latest version of the plugin (`3.1`) and the latest version of Taiga (`3.4`). Running my own instance with SSL activated.

Any ideas?
