### ISSUE TITLE
The synchronous operation of the plugin can destroy Taiga user experience.

### ISSUE THREAD

**Issue by oderwat** [taigaio/taiga-contrib-slack#74]
We had to remove the Slack plugin lately because a slow response of the Slack server resulted in an unusable Taiga. We had extrem long delays (up to 25s) and even some timeouts for simple actions like setting a Tag or changing an status. I even lost a comment because of a timeout.

This seems to be a result of the slack hook running synchronously and therefor taiga-back can't continue it's work while the Slack message is sent. I think that needs to be changed to make the plugin useable in a production environment.

**Comment by bameda** [comment]
Have you enable async mode in your taiga-back instance? 

You have to setup and enable celery in your `settings/local.py` to use async task in the server (plugins, webhooks, real time, importer, emails...)

More info at https://taigaio.github.io/taiga-doc/dist/setup-production.html#_async_tasks_optional

**Comment by oderwat** [comment]
Interesting... I actually have taiga-celery installed and running. But found `CELERY_ENABLED = True` being commented out in `local.py`. I enabled it now and will retry.
