### ISSUE TITLE
Update for Taiga 4.0 planned?

### ISSUE THREAD

**Issue by SkylordPhil** [taigaio/taiga-contrib-slack#75]
Since we updated our Taiga to 4.0.* we arent able to use this plugin and i wanted to know if an updated is planned and/or being worked on

**Comment by LaysDragon** [comment]
same question here...I guess they are busy on other thing...
can current version use on 4.x Taiga?

**Comment by LaysDragon** [comment]
oh yeah,it work fine in 4.1.12

**Comment by gianlucagilardi** [comment]
@LaysDragon  would you care to elaborate how you did install the plugin in order to make it work? tried bot prod and env methods as per readme but apparently it does not work...

**Comment by LaysDragon** [comment]
@gianlucagilardi You can take a look of branch of docker-taiga I made.Hope it can help you.
https://github.com/LaysDragon/docker-taiga/tree/slack

**Comment by migonzalvar** [comment]
I'm closing this issue because it seems everything is working on the last release, as of today, 5.5.1.
