### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by alexander-potemkin** [taigaio/taiga-contrib-slack#78]
Hi! Thank you for the plugin!

Is there any way you can support installation inside the Docker? Or, any, hopefully, plans to merge into the main source tree?

Best,
Alex.

**Comment by bameda** [comment]
Hi @alexander-potemkin, 

Currently the only solution is to create your own image with this contrib or search for one that [the community has created](https://tree.taiga.io/support/misc/community-contributions/#docker).

We are working on an official docker image for Taiga 6.0 that will contain this and other contrib plugins.

Regards.

**Comment by alexander-potemkin** [comment]
Thank you, @bameda! Any time estimate?

**Comment by madmath03** [comment]
Hi @alexander-potemkin 

If you want to use this plugin (and others) in a production docker image, you can use this one: https://github.com/Monogramm/docker-taiga

**Comment by yamila-moreno** [comment]
Hi @alexander-potemkin you can currently use taigaio/taiga-docker which includes taiga-contrib-slack integration out of the box.

Closing this issue.

**Comment by alexander-potemkin** [comment]
Thank you!
