### ISSUE TITLE
Does not work with Taiga 5.5

### ISSUE THREAD

**Issue by gramakri** [taigaio/taiga-contrib-slack#79]
With Taiga 5.0, the migration scripts run well:

```
# python manage.py migrate taiga_contrib_slack
Trying import local.py settings...
  Using LDAP
  Importing /app/data/customlocal.py
Operations to perform:
  Apply all migrations: taiga_contrib_slack
Running migrations:
  Applying taiga_contrib_slack.0001_initial... OK
  Applying taiga_contrib_slack.0002_slackhook_channel... OK
  Applying taiga_contrib_slack.0003_auto_20150923_1620... OK
  Applying taiga_contrib_slack.0004_auto_20160914_1420... OK
```

With taiga 5.5, it errors. Looks like maybe the plugin interface changed?

```
# python manage.py migrate taiga_contrib_slack
Trying import local.py settings...
  Using LDAP
  Importing /app/data/customlocal.py
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/app/code/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/code/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/app/code/taiga/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/app/code/taiga/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/app/code/taiga/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/app/code/taiga/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/code/taiga/lib/python3.6/site-packages/taiga_contrib_slack/models.py", line 22, in <module>
    class SlackHook(models.Model):
  File "/app/code/taiga/lib/python3.6/site-packages/taiga_contrib_slack/models.py", line 24, in SlackHook
    related_name="slackhooks")
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by migonzalvar** [comment]
Please, ensure you have the last version of taiga-contrib-slack installed. Maybe you need to `pip install --force-reinstall` to ensure this.

**Comment by gramakri** [comment]
@migonzalvar I have 3.1 installed. After your note, I see that there is now a 5.5.0. Is that version published? https://pypi.org/project/taiga-contrib-slack/ also says 3.1.

**Comment by gramakri** [comment]
```
install taiga-contrib-slack
ERROR: Could not find a version that satisfies the requirement taiga-contrib-slack==5.5.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 1.9.1, 1.10, 2.0, 2.1, 2.1.1, 3.0, 3.0.1, 3.0.2, 3.1)
ERROR: No matching distribution found for taiga-contrib-slack==5.5.0
```

**Comment by gramakri** [comment]
@migonzalvar OK, so it seems that `on_delete=models.CASCADE` is present in the 5.5.0 release but I guess it's not published on pypi? (Sorry, not a python expert, maybe I am doing something terribly wrong).

**Comment by jppmateus** [comment]
Also having the same problem. 

`(taiga) taiga@randomhost:~/taiga-back$ pip install --force-reinstall taiga-contrib-slack
Processing /home/taiga/.cache/pip/wheels/f7/45/b0/d7074b760ff7384bfa5f61e6da949e2e5e38d8afd4726cb523/taiga_contrib_slack-3.1-py3-none-any.whl
Installing collected packages: taiga-contrib-slack
  Attempting uninstall: taiga-contrib-slack
    Found existing installation: taiga-contrib-slack 3.1
    Uninstalling taiga-contrib-slack-3.1:
      Successfully uninstalled taiga-contrib-slack-3.1
Successfully installed taiga-contrib-slack-3.1
WARNING: You are using pip version 20.0.2; however, version 20.2.2 is available.
You should consider upgrading via the '/home/taiga/.virtualenvs/taiga/bin/python3 -m pip install --upgrade pip' command.
`

**Comment by jppmateus** [comment]
More information:

(taiga) taiga@randomhost:~/taiga-back$ pip search taiga-contrib-slack
taiga-contrib-slack (3.1)                   - The Taiga plugin for slack integration
  INSTALLED: 3.1 (latest)

**Comment by tomhollingworth** [comment]
I just pulled this repository and installed it. Didn't use the pip repositories. YMMV

```sh
$ cd /tmp
$ git clone https://github.com/taigaio/taiga-contrib-slack
Cloning into 'taiga-contrib-slack'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 835 (delta 1), reused 4 (delta 1), pack-reused 827
Receiving objects: 100% (835/835), 311.60 KiB | 2.53 MiB/s, done.
Resolving deltas: 100% (429/429), done.

$ cd taiga-contrib-slack/
$ cd back
$ pip install .
Processing /tmp/taiga-contrib-slack/back
Building wheels for collected packages: taiga-contrib-slack
  Building wheel for taiga-contrib-slack (setup.py) ... done
  Created wheel for taiga-contrib-slack: filename=taiga_contrib_slack-3.1-py3-none-any.whl size=28388 sha256=fe942319c103d0ebf23c1b413d49e65f5456902514fe48a67465af56e66a3ab4
  Stored in directory: /tmp/pip-ephem-wheel-cache-fy97pa7y/wheels/bb/62/11/a1664d24c5354bba5435c8eba2af38703e7a4e93f98dde6288
Successfully built taiga-contrib-slack
Installing collected packages: taiga-contrib-slack
Successfully installed taiga-contrib-slack-3.1

$ cd /opt/taiga-back
$ python manage.py migrate taiga_contrib_slack
Trying import local.py settings...
Operations to perform:
  Apply all migrations: taiga_contrib_slack
Running migrations:
  Applying taiga_contrib_slack.0001_initial... OK
  Applying taiga_contrib_slack.0002_slackhook_channel... OK
  Applying taiga_contrib_slack.0003_auto_20150923_1620... OK
  Applying taiga_contrib_slack.0004_auto_20160914_1420... OK
```

**Comment by jppmateus** [comment]
@tomhollingworth as I can see, you installed version 3.1. We are having issues with 5.5.0 version!

**Comment by albertososa95** [comment]
Hi at all! Since Django 2, 'on_delete' argument is required, so really it's not a Taiga issue. It would be fixed adding this argument on models.py.

**Comment by migonzalvar** [comment]
Meanwhile we do not make a new release available on PyPI, you could install front Gihub:

```
pip install --force-reinstall 'git+https://github.com/taigaio/taiga-contrib-slack.git@stable#egg=taiga-contrib-slack&subdirectory=back'
```

**Comment by tomhollingworth** [comment]
@jppmateus it actually installs Github tagged 5.5.0 version. The 3.1 your seeing in my shell output is due to [__init__.py](https://github.com/taigaio/taiga-contrib-slack/blob/f5ea01281f9dd8a4115aaaf5615921125334972d/back/taiga_contrib_slack/__init__.py#L18) it's still at 3.1, even though the Github repo is tagged at 5.5

@migonzalvar's command above is the way to go 👍

**Comment by jppmateus** [comment]
If I use the command provided by @migonzalvar, no update is made. Still on the same version. And still not working

**Comment by migonzalvar** [comment]
@jppmateus there is a new version in https://pypi.org/project/taiga-contrib-slack/ since Sep 21. Please try again

**Comment by jppmateus** [comment]
@migonzalvar it's working now. Thanks!

**Comment by gramakri** [comment]
Yup, same here. Will close this. Thanks!
