### ISSUE TITLE
Not getting messages in Mattermost

### ISSUE THREAD

**Issue by albertososa95** [taigaio/taiga-contrib-slack#80]
Hi at all! We've got self-hosted Taiga since 3.x version, deployed with Docker in our bussiness. In this week, we performed a Taiga upgrade to 5.5.5. All migrations runned without problems. Also, we've got Taiga integrated with Mattermost, that it was working perfectly until upgrade. In the plugin config page, we launch a test and it works, but no message is displayed in Mattermost when we make changes on Taiga projects (kanban/issues/wiki...).

taiga-contrib-slack was installed using pip, so we have the latest version available.

Any ideas?

**Comment by cinco** [comment]
hi @albertososa95 , did you find a solution? I'm going through the same problem. It works when testing on the plugin page, but I don't get notifications when US, issues and tasks are created or modified.
