### ISSUE TITLE
blocked_note_html gibberish in all new notifications

### ISSUE THREAD

**Issue by theworkerant** [taigaio/taiga-contrib-slack#9]
Something must have changed in the recent Taiga update because now our Slack channel gets normal updates plus some gibberish attached. See screenshot. Any ideas?

![captura de pantalla 2015-03-20 a las 11 26 22](https://cloud.githubusercontent.com/assets/58770/6753350/103eb3a4-cef4-11e4-9c02-75a9a986bb3f.png)

**Comment by lmerriam** [comment]
I notice it happens the first time someone makes any change to a task or issue (haven't tried a story yet). After that I won't see anything about blocked_note_html again from that task.

**Comment by bameda** [comment]
Yes, blocked note was added to the history entries recently and this (visual) bug was fixed here https://github.com/taigaio/taiga-contrib-slack/pull/8

We'll apply these changes in taiga.io asap
